---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/bookstock":
    get:
      summary: list bookstocks
      responses:
        '200':
          description: successful
    post:
      summary: create bookstock
      responses:
        '200':
          description: successful
  "/bookstock/new":
    get:
      summary: new bookstock
      responses:
        '200':
          description: successful
  "/bookstock/{id}/edit":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit bookstock
      responses:
        '200':
          description: successful
  "/bookstock/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show bookstock
      responses:
        '200':
          description: successful
    patch:
      summary: update bookstock
      responses:
        '200':
          description: successful
    put:
      summary: update bookstock
      responses:
        '200':
          description: successful
    delete:
      summary: delete bookstock
      responses:
        '200':
          description: successful
  "/searchbkauthor":
    get:
      summary: list searchbkauthors
      responses:
        '200':
          description: successful
    post:
      summary: create searchbkauthor
      responses:
        '200':
          description: successful
  "/searchbkauthor/new":
    get:
      summary: new searchbkauthor
      responses:
        '200':
          description: successful
  "/searchbkauthor/{id}/edit":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit searchbkauthor
      responses:
        '200':
          description: successful
  "/searchbkauthor/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show searchbkauthor
      responses:
        '200':
          description: successful
    patch:
      summary: update searchbkauthor
      responses:
        '200':
          description: successful
    put:
      summary: update searchbkauthor
      responses:
        '200':
          description: successful
    delete:
      summary: delete searchbkauthor
      responses:
        '200':
          description: successful
  "/searchbkname":
    get:
      summary: list searchbknames
      responses:
        '200':
          description: successful
    post:
      summary: create searchbkname
      responses:
        '200':
          description: successful
  "/searchbkname/new":
    get:
      summary: new searchbkname
      responses:
        '200':
          description: successful
  "/searchbkname/{id}/edit":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit searchbkname
      responses:
        '200':
          description: successful
  "/searchbkname/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show searchbkname
      responses:
        '200':
          description: successful
    patch:
      summary: update searchbkname
      responses:
        '200':
          description: successful
    put:
      summary: update searchbkname
      responses:
        '200':
          description: successful
    delete:
      summary: delete searchbkname
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
